# Generated by Django 4.2.7 on 2023-11-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
